---

antora:
  name: modules
  dir: www
  modules:
    - name: index
      label: Step 1
    - name: module-02
      label: Step 2
    - name: module-03
      label: Step 3
    - name: module-04
      label: Step 4
    - name: module-05
      label: Step 5
tabs:
  - name: ">_ Terminal root"
    port: 443
    path: /tty1
    user: root
    host: rhel
  - name: ">_ Terminal rhel"
    port: 443
    path: /tty2
    user: rhel
    host: rhel
